Add Dockerfile/Makefile
harvest-platform/esevaluator pull request #11
Opened 2016-11-25 15:19 UTC by gerpsh

Addresses #5 and #6

2016-11-26 22:05 UTC, bruth requested changes

2016-11-26 22:05 UTC, bruth commented on Makefile
> +	go build -o $(GOPATH)/bin/esevaluator ./cmd/esevaluator
Replace `esevaluator` with `$(PROG_NAME)`.

2016-11-26 22:05 UTC, bruth commented on Makefile
> +	gox -output="bin/esevaluator-{{.OS}}.{{.Arch}}" \
Change to `bin/{{.OS}}-{{.Arch}}/$(PROG_NAME)`, so the binary is the same name across platforms. This also corrects what `dist-zip` expects.

2016-11-26 22:05 UTC, bruth commented on Dockerfile
> +FROM golang:latest
The Dockerfile can be as simple as:

```
FROM scratch
COPY ./dist/linux-amd64/esevaluator /app
EXPOSE 8080
ENTRYPOINT ["/app"]
```

This relies on an up-to-date distribution build and adds an `ENTRYPOINT` so a container can be run with the program as the entrypoint (yup). This allows for:

```
docker run -v ./tls:/tls -p 8080:8080 -d harvest-platform/esevaluator -tlscert /tls/cert.pem -tlskey /tls/key.pem
```

2016-11-28 16:54 UTC, gerpsh commented on Dockerfile
> +FROM golang:latest
This requires an already existent TLS directory with certs as well?

2016-11-28 17:50 UTC, bruth commented on Dockerfile
> +FROM golang:latest
No, the `-v ./tls:/tls` effectively creates a mount point for the directory whether or it exists.

2016-11-28 20:28 UTC, bruth commented on Makefile
> +	gox -output="./dist/{{.OS}}.{{.Arch}}/$(PROG_NAME)" \
`dist-zip` expects the directory names to use hyphens not periods.

2016-11-28 20:35 UTC, bruth commented on Makefile
> +dist: dist-build dist-zip
Might as well define a `docker` target that builds the image and include the target here.

2016-11-29 16:25 UTC, gerpsh commented on Makefile
> +dist: dist-build dist-zip
Addressed in 00c01ad

2016-11-29 16:26 UTC, bruth commented on Makefile
> +dist: dist-build dist-zip
This line should say `dist: dist-build dist-zip docker`

2016-11-29 16:27 UTC, bruth commented on Makefile
> +dist: dist-build dist-zip
And you can remove the `dist-build` dep for the `docker` target. The reasoning is when `dist` is called, all artifacts should be built.

2016-11-29 16:33 UTC, bruth commented on Makefile
> +docker: dist-build
Stating this again in case the previous comment got lost. Remove `dist-build` from this target.

2016-11-30 14:57 UTC, bruth commented on transport/http.go
> +	writeResponse(w, http.StatusOK, resp)
This already handles writing the content-type header and status code. No need for the two lines above.

2016-11-30 18:09 UTC, bruth commented on Makefile
> +		go run $(GOROOT)/src/crypto/tls/generate_cert.go --host localhost; \
Change `$(GOROOT)` to `$(shell go env GOROOT)`.

2016-11-30 18:12 UTC, bruth commented on cmd/esevaluator/main.go
>  	flag.StringVar(&tlskey, "tlskey", "", "Path to TLS key.")
`flag.Parse()` needs to come after the flags are defined 😉

2016-11-30 18:15 UTC, bruth commented on Dockerfile
> +ENTRYPOINT ["/app"]
Add a `CMD ["0.0.0.0:8080"]` so the container is listening to all interfaces, otherwise it won't be able to communicate outside of the container.

2016-11-30 18:16 UTC, bruth commented on Dockerfile
> +ENTRYPOINT ["/app"]
I am seeing all these things now, because I cloned and am testing it locally.

2016-11-30 18:19 UTC, bruth commented on transport/http.go
> +	return
No need to return nothing.

2016-12-02 14:16 UTC, merged